# Generated by Django 3.2.8 on 2022-03-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20220313_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='categories',
        ),
        migrations.AddField(
            model_name='project',
            name='Newsfeed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
