# Generated by Django 3.2.8 on 2022-03-13 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20220313_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Newsfeed',
            new_name='newsfeed',
        ),
    ]
