# Generated by Django 3.2.8 on 2022-03-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_newsfeed_project_newsfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='newsfeed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
